kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-server
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
