apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "promtail.fullname" . }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "promtail.fullname" . }}
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: {{ .Release.Namespace | quote }}
